version: '2'
services:
  hubot:
    image: him0.net:5000/bitchan
    command: bin/hubot --adapter slack
    volumes:
      - .:/myapp
    depends_on:
      - redis
    environment:
      HUBOT_SLACK_BOTNAME: bitchan
      HUBOT_SLACK_TEAM: udon-cryptocurrency
      HUBOT_SLACK_TOKEN: xoxb-43081078674-7hHw5WybdlvwsY9eabe3y6QO
      TZ: Asia/Tokyo
  redis:
    image: redis:latest
